# Generated by Django 3.1 on 2020-10-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoModule', '0002_auto_20200923_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='file',
            field=models.URLField(),
        ),
    ]
